ITEM_JIGGY = "Jiggy"

ITEM_JUMP = "Jump"
ITEM_FEATHERY_FLAP = "Feathery Flap"
ITEM_FLAP_FLIP = "Flap Flip"
ITEM_CLAW_SWIPE = "Claw Swipe"
ITEM_ROLL = "Roll"
ITEM_RAT_A_TAT_RAP = "Rat-a-Tat Rap"
ITEM_CLIMB = "Climb"
ITEM_SWIM = "Swim"
ITEM_BEAK_BARGE = "Beak Barge"

ITEM_TALON_TROT = "Talon Trot"
ITEM_TALON_TROT_SPEED_UPGRADE = "Talon Trot Speed Upgrade"
ITEM_EGGS = "Eggs"
ITEM_BEAK_BUSTER = "Beak Buster"
ITEM_TERMITE_TRANSFORMATION = "Termite Transformation"

ITEM_FLIGHT = "Flight"
ITEM_SHOCK_SPRING_JUMP = "Shock Spring Jump"

ITEM_BLUBBER_GOLD = "Blubber's Gold"

ITEM_WONDERWING = "Wonderwing"

ITEM_STILT_STRIDE = "Stilt Stride"
ITEM_CROCODILE_TRANSFORMATION = "Crocodile Transformation"

ITEM_BEAK_BOMB = "Beak Bomb"
ITEM_WALRUS_TRANSFORMATION = "Walrus Transformation"

ITEM_TURBO_TALON_TROT = "Turbo Talon Trot"

ITEM_PUMPKIN_TRANSFORMATION = "Pumpkin Transformation"

ITEM_BEE_TRANSFORMATION = "Bee Transformation"

ITEM_RED_PRESENT = "Red Present"
ITEM_BLUE_PRESENT = "Blue Present"
ITEM_GREEN_PRESENT = "Green Present"

ITEM_CATERPILLAR = "Caterpillar"
ITEM_ACORN = "Acorn"

ITEM_MM_BLUE_JINJO = "Mumbo's Mountain Blue Jinjo"
ITEM_MM_GREEN_JINJO = "Mumbo's Mountain Green Jinjo"
ITEM_MM_ORANGE_JINJO = "Mumbo's Mountain Orange Jinjo"
ITEM_MM_PURPLE_JINJO = "Mumbo's Mountain Purple Jinjo"
ITEM_MM_YELLOW_JINJO = "Mumbo's Mountain Yellow Jinjo"

ITEM_TTC_BLUE_JINJO = "Treasure Trove Cove Blue Jinjo"
ITEM_TTC_GREEN_JINJO = "Treasure Trove Cove Green Jinjo"
ITEM_TTC_ORANGE_JINJO = "Treasure Trove Cove Orange Jinjo"
ITEM_TTC_PURPLE_JINJO = "Treasure Trove Cove Purple Jinjo"
ITEM_TTC_YELLOW_JINJO = "Treasure Trove Cove Yellow Jinjo"

ITEM_CC_BLUE_JINJO = "Clanker's Cavern Blue Jinjo"
ITEM_CC_GREEN_JINJO = "Clanker's Cavern Green Jinjo"
ITEM_CC_ORANGE_JINJO = "Clanker's Cavern Orange Jinjo"
ITEM_CC_PURPLE_JINJO = "Clanker's Cavern Purple Jinjo"
ITEM_CC_YELLOW_JINJO = "Clanker's Cavern Yellow Jinjo"

ITEM_BGS_BLUE_JINJO = "Bubblegloop Swamp Blue Jinjo"
ITEM_BGS_GREEN_JINJO = "Bubblegloop Swamp Green Jinjo"
ITEM_BGS_ORANGE_JINJO = "Bubblegloop Swamp Orange Jinjo"
ITEM_BGS_PURPLE_JINJO = "Bubblegloop Swamp Purple Jinjo"
ITEM_BGS_YELLOW_JINJO = "Bubblegloop Swamp Yellow Jinjo"

ITEM_FP_BLUE_JINJO = "Freezeezy Peak Blue Jinjo"
ITEM_FP_GREEN_JINJO = "Freezeezy Peak Green Jinjo"
ITEM_FP_ORANGE_JINJO = "Freezeezy Peak Orange Jinjo"
ITEM_FP_PURPLE_JINJO = "Freezeezy Peak Purple Jinjo"
ITEM_FP_YELLOW_JINJO = "Freezeezy Peak Yellow Jinjo"

ITEM_GV_BLUE_JINJO = "Gobi's Valley Blue Jinjo"
ITEM_GV_GREEN_JINJO = "Gobi's Valley Green Jinjo"
ITEM_GV_ORANGE_JINJO = "Gobi's Valley Orange Jinjo"
ITEM_GV_PURPLE_JINJO = "Gobi's Valley Purple Jinjo"
ITEM_GV_YELLOW_JINJO = "Gobi's Valley Yellow Jinjo"

ITEM_MMM_BLUE_JINJO = "Mad Monster Mansion Blue Jinjo"
ITEM_MMM_GREEN_JINJO = "Mad Monster Mansion Green Jinjo"
ITEM_MMM_ORANGE_JINJO = "Mad Monster Mansion Orange Jinjo"
ITEM_MMM_PURPLE_JINJO = "Mad Monster Mansion Purple Jinjo"
ITEM_MMM_YELLOW_JINJO = "Mad Monster Mansion Yellow Jinjo"

ITEM_RBB_BLUE_JINJO = "Rusty Bucket Bay Blue Jinjo"
ITEM_RBB_GREEN_JINJO = "Rusty Bucket Bay Green Jinjo"
ITEM_RBB_ORANGE_JINJO = "Rusty Bucket Bay Orange Jinjo"
ITEM_RBB_PURPLE_JINJO = "Rusty Bucket Bay Purple Jinjo"
ITEM_RBB_YELLOW_JINJO = "Rusty Bucket Bay Yellow Jinjo"

ITEM_CCW_BLUE_JINJO = "Click Clock Wood Blue Jinjo"
ITEM_CCW_GREEN_JINJO = "Click Clock Wood Green Jinjo"
ITEM_CCW_ORANGE_JINJO = "Click Clock Wood Orange Jinjo"
ITEM_CCW_PURPLE_JINJO = "Click Clock Wood Purple Jinjo"
ITEM_CCW_YELLOW_JINJO = "Click Clock Wood Yellow Jinjo"

ITEM_EGG_REFILL = "Egg Refill"
ITEM_REDFEATHER_REFILL = "Red Feather Refill"
ITEM_GOLDFEATHER_REFILL = "Gold Feather Refill"

ITEM_VICTORY = "Victory"

LOC_EMPTY_HONEYCOMB_SM_LOG = "SM Empty Honeycomb Piece on Log"
LOC_EMPTY_HONEYCOMB_SM_WATERFALL = "SM Empty Honeycomb Piece Behind Waterfall"
LOC_EMPTY_HONEYCOMB_SM_TREE = "SM Empty Honeycomb Piece Atop Tree"
LOC_EMPTY_HONEYCOMB_SM_UNDERWATER = "SM Underwater Empty Honeycomb Piece"
LOC_EMPTY_HONEYCOMB_SM_ROCK = "SM Rock Empty Honeycomb Piece"
LOC_EMPTY_HONEYCOMB_SM_COLLIWOBBLE = "SM Colliwobble Empty Honeycomb Piece"

LOC_JIGGY_GL_ENTRYWAY = "GL Entryway Jiggy"
LOC_JIGGY_GL_ATOP_MUMBOS_MOUNTAIN = "GL Atop Mumbo's Mountain Jiggy"
LOC_JIGGY_GL_TTC_CANNON = "GL TTC Cannon Jiggy"
LOC_JIGGY_GL_EYE_SWITCHES = "GL Eye Switches Jiggy"
LOC_JIGGY_GL_WITCHS_HAT = "GL Witch's Hat Jiggy"
LOC_JIGGY_GL_ABOVE_FP = "GL Above Freezeezy Peak Jiggy"
LOC_JIGGY_GL_SARCOPHAGUS = "GL Sarcophagus Jiggy"
LOC_JIGGY_GL_GRUNTYS_EYE = "GL Grunty's Eye Jiggy"
LOC_JIGGY_GL_WATER_SWITCH = "GL Water Switch Jiggy"
LOC_JIGGY_GL_BEE_TREE = "GL Bee Tree Jiggy"
LOC_MUMBO_TOKEN_GL_RED_CAULDRON = "GL Mumbo Token Behind Red Cauldron"
LOC_MUMBO_TOKEN_GL_DRAIN_PIPE = "GL Mumbo Token Above Drain Pipe"
LOC_MUMBO_TOKEN_GL_CCW_PODIUM = "GL Mumbo Token Near CCW Jiggy Podium"
LOC_MUMBO_TOKEN_GL_ABOVE_CC = "GL Mumbo Token Above CC Entrance"

LOC_JIGGY_MM_CONGA_ORANGE_THROW = "MM Conga Orange Throw Jiggy"
LOC_JIGGY_MM_CHIMPY_ORANGE = "MM Chimpy Orange Jiggy"
LOC_JIGGY_MM_CONGA_ATTACK = "MM Conga Attack Jiggy"
LOC_JIGGY_MM_HILLSIDE = "MM Hillside Jiggy"
LOC_JIGGY_MM_MUMBOS_HUT = "MM Mumbo's Hut Jiggy"
LOC_JIGGY_MM_TOTEM_POLE = "MM Totem Pole Jiggy"
LOC_JIGGY_MM_STONEHENGE = "MM Stonehenge Jiggy"
LOC_JIGGY_MM_HUT = "MM Hut Jiggy"
LOC_JIGGY_MM_MOUNTAINTOP = "MM Mountaintop Jiggy"
LOC_JIGGY_MM_JINJO = "MM Jinjo Jiggy"
LOC_EMPTY_HONEYCOMB_MM_HILLSIDE = "MM Hillside Empty Honeycomb Piece"
LOC_EMPTY_HONEYCOMB_MM_TOTEM = "MM Totem Empty Honeycomb Piece"
LOC_MUMBO_TOKEN_MM_ENTRANCE = "MM Entrance Mumbo Token"
LOC_MUMBO_TOKEN_MM_CHIMPY = "MM Chimpy Mumbo Token"
LOC_MUMBO_TOKEN_MM_STONEHENGE = "MM Stonehenge Mumbo Token"
LOC_MUMBO_TOKEN_MM_MUMBOS_HUT = "MM Mumbo Token Near Mumbo's Hut"
LOC_MUMBO_TOKEN_MM_TERMITE_MOUND = "MM Termite Mound Mumbo Token"

LOC_JIGGY_TTC_NIPPER = "TTC Nipper Jiggy"
LOC_JIGGY_TTC_BLUBBER = "TTC Blubber Jiggy"
LOC_JIGGY_TTC_SANDCASTLE = "TTC Sandcastle Jiggy"
LOC_JIGGY_TTC_SHOCK_SPRING = "TTC Shock Spring Jump Jiggy"
LOC_JIGGY_TTC_X_MARK = "TTC X Marks the Spot Jiggy"
LOC_JIGGY_TTC_POOL = "TTC Pool Jiggy"
LOC_JIGGY_TTC_CLIFFSIDE = "TTC Cliffside Jiggy"
LOC_JIGGY_TTC_LOCKUP = "TTC Lockup Jiggy"
LOC_JIGGY_TTC_LIGHTHOUSE = "TTC Lighthouse Jiggy"
LOC_JIGGY_TTC_JINJO = "TTC Jinjo Jiggy"
LOC_EMPTY_HONEYCOMB_TTC_UNDERWATER = "TTC Underwater Empty Honeycomb Piece"
LOC_EMPTY_HONEYCOMB_TTC_CRATE = "TTC Empty Honeycomb Piece Atop Floating Crate"
LOC_MUMBO_TOKEN_TTC_NIPPER = "TTC Mumbo Token Behind Nipper"
LOC_MUMBO_TOKEN_TTC_MAST = "TTC Mumbo Token on Ship Mast"
LOC_MUMBO_TOKEN_TTC_HOLD = "TTC Mumbo Token in Ship's Hold"
LOC_MUMBO_TOKEN_TTC_SHOCK_SPRING = "TTC Shock Spring Jump Mumbo Token"
LOC_MUMBO_TOKEN_TTC_X_MARK = "TTC Shock Spring Jump Mumbo Token"
LOC_MUMBO_TOKEN_TTC_LOCKUP_LEFT = "TTC Lockup Left Mumbo Token"
LOC_MUMBO_TOKEN_TTC_LOCKUP_RIGHT = "TTC Lockup Right Mumbo Token"
LOC_MUMBO_TOKEN_TTC_POOL = "TTC Underwater Pool Mumbo Token"
LOC_MUMBO_TOKEN_TTC_CRATE = "TTC Mumbo Token Atop Floating Crate"
LOC_MUMBO_TOKEN_TTC_LIGHTHOUSE = "TTC Lighthouse Mumbo Token"

LOC_JIGGY_CC_CLANKER_RAISE = "CC Clanker Raise Jiggy"
LOC_JIGGY_CC_CLANKER_TAIL = "CC Above Clanker's Tail Jiggy"
LOC_JIGGY_CC_CLANKER_BOLT = "CC Above Clanker's Bolt Jiggy"
LOC_JIGGY_CC_CLANKER_GOLD_TEETH = "CC Clanker's Gold Teeth Jiggy"
LOC_JIGGY_CC_CLANKER_BLOWHOLE = "CC Inside Clanker's Blowhole Jiggy"
LOC_JIGGY_CC_WONDERWING = "CC Wonderwing Jiggy"
LOC_JIGGY_CC_STOMACH_RINGS = "CC Stomach Rings Jiggy"
LOC_JIGGY_CC_SNIPPET = "CC Snippet Jiggy"
LOC_JIGGY_CC_UNDERWATER_TUNNEL = "CC Underwater Tunnel Jiggy"
LOC_JIGGY_CC_JINJO = "CC Jinjo Jiggy"
LOC_EMPTY_HONEYCOMB_CC_PIPE = "CC Empty Honeycomb Piece Inside Pipe"
LOC_EMPTY_HONEYCOMB_CC_GRATE = "CC Wall Grate Empty Honeycomb Piece"
LOC_MUMBO_TOKEN_CC_ENTRANCE = "CC Mumbo Token Above Entrance"
LOC_MUMBO_TOKEN_CC_CLANKER_TAIL = "CC Mumbo Token Above Clanker's Tail"
LOC_MUMBO_TOKEN_CC_CLANKER_GOLD_TEETH = "CC Clanker's Gold Teeth Mumbo Token"
LOC_MUMBO_TOKEN_CC_GRATE = "CC Wall Grate Mumbo Token"
LOC_MUMBO_TOKEN_CC_UNDERWATER_TUNNEL = "CC Underwater Tunnel Mumbo Token"

LOC_JIGGY_BGS_EGG = "BGS Egg Jiggy"
LOC_JIGGY_BGS_CENTER_RACE = "BGS Central Area Race Jiggy"
LOC_JIGGY_BGS_FLIBBET = "BGS Flibbet Jiggy"
LOC_JIGGY_BGS_TANKTUP = "BGS Tanktup Jiggy"
LOC_JIGGY_BGS_TIPTUP = "BGS Tiptup Jiggy"
LOC_JIGGY_BGS_HUT = "BGS Hut Jiggy"
LOC_JIGGY_BGS_MUMBOS_HUT_RACE = "BGS Race Near Mumbo's Hut Jiggy"
LOC_JIGGY_BGS_CROCTUS = "BGS Croctus Jiggy"
LOC_JIGGY_BGS_MR_VILE = "BGS Mr. Vile's Jiggy"
LOC_JIGGY_BGS_JINJO = "BGS Jinjo Jiggy"

LOC_JIGGY_FP_SIR_SLUSH = "FP Sir Slush Jiggy"
LOC_JIGGY_FP_SNOWMAN_PIPE = "FP Snowman's Pipe Jiggy"
LOC_JIGGY_FP_TOBOGGAN = "FP Boggy's Toboggan Jiggy"
LOC_JIGGY_FP_SNOWMAN_BUTTONS = "FP Snowman's Buttons Jiggy"
LOC_JIGGY_FP_CHRISTMAS_TREE = "FP Christmas Tree Jiggy"
LOC_JIGGY_FP_WOZZA = "FP Wozza's Jiggy"
LOC_JIGGY_FP_PRESENTS = "FP Presents Jiggy"
LOC_JIGGY_FP_BOGGY_RACE_1 = "FP Boogy Race 1 Jiggy"
LOC_JIGGY_FP_BOGGY_RACE_2 = "FP Boggy Race 2 Jiggy"
LOC_JIGGY_FP_JINJO = "FP Jinjo Jiggy"

LOC_JIGGY_GV_JINXY = "GV Jinxy's Jiggy"
LOC_JIGGY_GV_GRABBA = "GV Grabba's Jiggy"
LOC_JIGGY_GV_FLIP_PANELS = "GV Flip Panel Pyramid Jiggy"
LOC_JIGGY_GV_WATER_PYRAMID = "GV Water Pyramid Jiggy"
LOC_JIGGY_GV_ANCIENT_ONES = "GV Ancient Ones' Jiggy"
LOC_JIGGY_GV_RUBEE = "GV Rubee's Jiggy"
LOC_JIGGY_GV_SANDYBUTT = "GV Sandybutt's Jiggy"
LOC_JIGGY_GV_GOBI = "GV Gobi's Jiggy"
LOC_JIGGY_GV_TRUNKER = "GV Trunker's Jiggy"
LOC_JIGGY_GV_JINJO = "GV Jinjo Jiggy"

LOC_JIGGY_MMM_NAPPER = "MMM Napper's Jiggy"
LOC_JIGGY_MMM_CELLAR = "MMM Cellar Jiggy"
LOC_JIGGY_MMM_TUMBLAR = "MMM Tumblar's Jiggy"
LOC_JIGGY_MMM_WELL = "MMM Well Jiggy"
LOC_JIGGY_MMM_FLOWERPOT = "MMM Flowerpot Jiggy"
LOC_JIGGY_MMM_CLOCK_TOWER = "MMM Clock Tower Jiggy"
LOC_JIGGY_MMM_MOTZAND = "MMM Motzand's Jiggy"
LOC_JIGGY_MMM_LOGGO = "MMM Loggo's Jiggy"
LOC_JIGGY_MMM_STORM_DRAIN = "MMM Storm Drain Jiggy"
LOC_JIGGY_MMM_JINJO = "GV Jinjo Jiggy"

LOC_JIGGY_RBB_SMOKESTACK = "RBB Smokestack Jiggy"
LOC_JIGGY_RBB_WHISTLE = "RBB Whistle Jiggy"
LOC_JIGGY_RBB_WAREHOUSE = "RBB Warehouse Jiggy"
LOC_JIGGY_RBB_METAL_CAGE = "RBB Metal Cage Jiggy"
LOC_JIGGY_RBB_CAPTAINS_ROOM = "RBB Captain's Room Jiggy"
LOC_JIGGY_RBB_BOSS_BOOM_BOX = "RBB Boss Boom Box's Jiggy"
LOC_JIGGY_RBB_SNORKEL = "RBB Snorkel's Jiggy"
LOC_JIGGY_RBB_ENGINE_ROOM = "RBB Engine Room Jiggy"
LOC_JIGGY_RBB_PROPELLER = "RBB Propeller Jiggy"
LOC_JIGGY_RBB_JINJO = "RBB Jinjo Jiggy"

LOC_JIGGY_CCW_TREETOP_ROOM = "CCW Treetop Room Jiggy"
LOC_JIGGY_CCW_TREETOP_SNAREBEAR = "CCW Treetop Snarebear Jiggy"
LOC_JIGGY_CCW_ZUBBA = "CCW Zubbas' Jiggy"
LOC_JIGGY_CCW_LEAVES = "CCW Summer Leaves Jiggy"
LOC_JIGGY_CCW_CABIN = "CCW Cabin Jiggy"
LOC_JIGGY_CCW_GNAWTY = "CCW Gnawty's Jiggy"
LOC_JIGGY_CCW_PLANT = "CCW Plant Jiggy"
LOC_JIGGY_CCW_NABNUTS = "CCW Nabnuts' Jiggy"
LOC_JIGGY_CCW_EYRIE = "CCW Eyrie's Jiggy"
LOC_JIGGY_CCW_JINJO = "CCW Jinjo Jiggy"

LOC_DEFEAT_GRUNTILDA = "Defeat Gruntilda"

RGN_MENU = "Menu"
RGN_SPIRAL_MOUNTAIN = "Spiral Mountain"
RGN_GRUNTILDAS_LAIR = "Gruntilda's Lair"
RGN_MUMBOS_MOUNTAIN = "Mumbo's Mountain"
RGN_TREASURE_TROVE_COVE = "Treasure Trove Cove"
RGN_CLANKERS_CAVERN = "Clanker's Cavern"
RGN_BUBBLEGLOOP_SWAMP = "Bubblegloop Swamp"
RGN_FREEZEEZY_PEAK = "Freezeezy Peak"
RGN_GOBIS_VALLEY = "Gobi's Valley"
RGN_MAD_MONSTER_MANSION = "Mad Monster Mansion"
RGN_RUSTY_BUCKET_BAY = "Rusty Bucket Bay"
RGN_CLICK_CLOCK_WOOD = "Click Clock Wood"