ITEM_JIGGY = "Jiggy"

ITEM_JUMP = "Jump"
ITEM_FEATHERY_FLAP = "Feathery Flap"
ITEM_FLAP_FLIP = "Flap Flip"
ITEM_CLAW_SWIPE = "Claw Swipe"
ITEM_ROLL = "Roll"
ITEM_RAT_A_TAT_RAP = "Rat-a-Tat Rap"
ITEM_CLIMB = "Climb"
ITEM_SWIM = "Swim"
ITEM_BEAK_BARGE = "Beak Barge"

ITEM_TALON_TROT = "Talon Trot"
ITEM_TALON_TROT_SPEED_UPGRADE = "Talon Trot Speed Upgrade"
ITEM_EGGS = "Eggs"
ITEM_BEAK_BUSTER = "Beak Buster"
ITEM_TERMITE_TRANSFORMATION = "Termite Transformation"

ITEM_FLIGHT = "Flight"
ITEM_SHOCK_SPRING_JUMP = "Shock Spring Jump"

ITEM_WONDERWING = "Wonderwing"

ITEM_MM_BLUE_JINJO = "Mumbo's Mountain Blue Jinjo"
ITEM_MM_GREEN_JINJO = "Mumbo's Mountain Green Jinjo"
ITEM_MM_ORANGE_JINJO = "Mumbo's Mountain Orange Jinjo"
ITEM_MM_PURPLE_JINJO = "Mumbo's Mountain Purple Jinjo"
ITEM_MM_YELLOW_JINJO = "Mumbo's Mountain Yellow Jinjo"

ITEM_TTC_BLUE_JINJO = "Treasure Trove Cove Blue Jinjo"
ITEM_TTC_GREEN_JINJO = "Treasure Trove Cove Green Jinjo"
ITEM_TTC_ORANGE_JINJO = "Treasure Trove Cove Orange Jinjo"
ITEM_TTC_PURPLE_JINJO = "Treasure Trove Cove Purple Jinjo"
ITEM_TTC_YELLOW_JINJO = "Treasure Trove Cove Yellow Jinjo"

ITEM_CC_BLUE_JINJO = "Clanker's Cavern Blue Jinjo"
ITEM_CC_GREEN_JINJO = "Clanker's Cavern Green Jinjo"
ITEM_CC_ORANGE_JINJO = "Clanker's Cavern Orange Jinjo"
ITEM_CC_PURPLE_JINJO = "Clanker's Cavern Purple Jinjo"
ITEM_CC_YELLOW_JINJO = "Clanker's Cavern Yellow Jinjo"

ITEM_BS_BLUE_JINJO = "Bubblegloop Swamp Blue Jinjo"
ITEM_BS_GREEN_JINJO = "Bubblegloop Swamp Green Jinjo"
ITEM_BS_ORANGE_JINJO = "Bubblegloop Swamp Orange Jinjo"
ITEM_BS_PURPLE_JINJO = "Bubblegloop Swamp Purple Jinjo"
ITEM_BS_YELLOW_JINJO = "Bubblegloop Swamp Yellow Jinjo"

ITEM_FP_BLUE_JINJO = "Freezeezy Peak Blue Jinjo"
ITEM_FP_GREEN_JINJO = "Freezeezy Peak Green Jinjo"
ITEM_FP_ORANGE_JINJO = "Freezeezy Peak Orange Jinjo"
ITEM_FP_PURPLE_JINJO = "Freezeezy Peak Purple Jinjo"
ITEM_FP_YELLOW_JINJO = "Freezeezy Peak Yellow Jinjo"

ITEM_GV_BLUE_JINJO = "Gobi's Valley Blue Jinjo"
ITEM_GV_GREEN_JINJO = "Gobi's Valley Green Jinjo"
ITEM_GV_ORANGE_JINJO = "Gobi's Valley Orange Jinjo"
ITEM_GV_PURPLE_JINJO = "Gobi's Valley Purple Jinjo"
ITEM_GV_YELLOW_JINJO = "Gobi's Valley Yellow Jinjo"

ITEM_MMM_BLUE_JINJO = "Mad Monster Mansion Blue Jinjo"
ITEM_MMM_GREEN_JINJO = "Mad Monster Mansion Green Jinjo"
ITEM_MMM_ORANGE_JINJO = "Mad Monster Mansion Orange Jinjo"
ITEM_MMM_PURPLE_JINJO = "Mad Monster Mansion Purple Jinjo"
ITEM_MMM_YELLOW_JINJO = "Mad Monster Mansion Yellow Jinjo"

ITEM_RBB_BLUE_JINJO = "Rusty Bucket Bay Blue Jinjo"
ITEM_RBB_GREEN_JINJO = "Rusty Bucket Bay Green Jinjo"
ITEM_RBB_ORANGE_JINJO = "Rusty Bucket Bay Orange Jinjo"
ITEM_RBB_PURPLE_JINJO = "Rusty Bucket Bay Purple Jinjo"
ITEM_RBB_YELLOW_JINJO = "Rusty Bucket Bay Yellow Jinjo"

ITEM_CCW_BLUE_JINJO = "Click Clock Wood Blue Jinjo"
ITEM_CCW_GREEN_JINJO = "Click Clock Wood Green Jinjo"
ITEM_CCW_ORANGE_JINJO = "Click Clock Wood Orange Jinjo"
ITEM_CCW_PURPLE_JINJO = "Click Clock Wood Purple Jinjo"
ITEM_CCW_YELLOW_JINJO = "Click Clock Wood Yellow Jinjo"

ITEM_EGG_REFILL = "Egg Refill"
ITEM_REDFEATHER_REFILL = "Red Feather Refill"
ITEM_GOLDFEATHER_REFILL = "Gold Feather Refill"

ITEM_VICTORY = "Victory"

LOC_JIGGY_GL_ENTRYWAY = "GLF1 Entryway Jiggy"
LOC_JIGGY_GL_ATOP_MUMBOS_MOUNTAIN = "GLF1 Atop Mumbo's Mountain Jiggy"
LOC_JIGGY_GL_TTC_CANNON = "GLF3 TTC Cannon Jiggy"
LOC_JIGGY_GL_CC_EYE_SWITCHES = "GLF2 Eye Switches Jiggy"

LOC_JIGGY_MM_CONGA_ORANGE_THROW = "MM Conga Orange Throw Jiggy"
LOC_JIGGY_MM_CHIMPY_ORANGE = "MM Chimpy Orange Jiggy"
LOC_JIGGY_MM_CONGA_ATTACK = "MM Conga Attack Jiggy"
LOC_JIGGY_MM_HILLSIDE = "MM Hillside Jiggy"
LOC_JIGGY_MM_MUMBOS_HUT = "MM Mumbo's Hut Jiggy"
LOC_JIGGY_MM_TOTEM_POLE = "MM Totem Pole Jiggy"
LOC_JIGGY_MM_STONEHENGE = "MM Stonehenge Jiggy"
LOC_JIGGY_MM_HUT = "MM Hut Jiggy"
LOC_JIGGY_MM_MOUNTAINTOP = "MM Mountaintop Jiggy"
LOC_JIGGY_MM_JINJO = "MM Jinjo Jiggy"

LOC_JIGGY_TTC_NIPPER = "TTC Nipper Jiggy"
LOC_JIGGY_TTC_BLUBBER = "TTC Blubber Jiggy"
LOC_JIGGY_TTC_SANDCASTLE = "TTC Sandcastle Jiggy"
LOC_JIGGY_TTC_SHOCK_SPRING = "TTC Shock Spring Jump Jiggy"
LOC_JIGGY_TTC_X_MARK = "TTC X Marks the Spot Jiggy"
LOC_JIGGY_TTC_POOL = "TTC Pool Jiggy"
LOC_JIGGY_TTC_CLIFFSIDE = "TTC Cliffside Jiggy"
LOC_JIGGY_TTC_LOCKUP = "TTC Lockup Jiggy"
LOC_JIGGY_TTC_LIGHTHOUSE = "TTC Lighthouse Jiggy"
LOC_JIGGY_TTC_JINJO = "TTC Jinjo Jiggy"

LOC_JIGGY_CC_CLANKER_RAISE = "CC Clanker Raise Jiggy"
LOC_JIGGY_CC_CLANKER_TAIL = "CC Above Clanker's Tail Jiggy"
LOC_JIGGY_CC_CLANKER_BOLT = "CC Above Clanker's Bolt Jiggy"
LOC_JIGGY_CC_CLANKER_GOLD_TEETH = "CC Clanker's Gold Teeth Jiggy"
LOC_JIGGY_CC_CLANKER_BLOWHOLE = "CC Inside Clanker's Blowhole Jiggy"
LOC_JIGGY_CC_WONDERWING = "CC Wonderwing Jiggy"
LOC_JIGGY_CC_STOMACH_RINGS = "CC Stomach Rings Jiggy"
LOC_JIGGY_CC_SNIPPET = "CC Snippet Jiggy"
LOC_JIGGY_CC_UNDERWATER_TUNNEL = "CC Underwater Tunnel Jiggy"
LOC_JIGGY_CC_JINJO = "CC Jinjo Jiggy"

LOC_DEFEAT_GRUNTILDA = "Defeat Gruntilda"

RGN_MENU = "Menu"
RGN_SPIRAL_MOUNTAIN = "Spiral Mountain"
RGN_GRUNTILDAS_LAIR = "Gruntilda's Lair"
RGN_MUMBOS_MOUNTAIN = "Mumbo's Mountain"