import typing

from BaseClasses import Location

class BKLocation(Location):
    game = "Banjo-Kazooie"

class LocationData(typing.NamedTuple):
    address: int
    requirements: typing.Optional[typing.List[typing.List[str]]] = None


location_table = {
    "Jump Molehill": LocationData(120000),
    "Swim Molehill": LocationData(120001),
    "Climb Molehill": LocationData(120002),
    "Beak Barge Molehill": LocationData(120003),
    "Attack Molehill": LocationData(120004),
    "SM Jump Honeycomb Piece": LocationData(120005, [["Jump", "Feathery Flap"], ["Flap Flip"]]),
    "SM Waterfall Honeycomb Piece": LocationData(120006, [["Jump", "Feathery Flap"], ["Jump", "Rat-A-Tat Rap"]]),
    "SM Tree Honeycomb Piece": LocationData(120007, [["Climb"]]),
    "SM Underwater Honeycomb Piece": LocationData(120008, [["Swim"]]),
    "SM Beak Barge Honeycomb Piece": LocationData(120009, [["Beak Barge"]]),
    "SM Combat Honeycomb Piece": LocationData(120010, [["Claw Swipe"], ["Roll"], ["Rat-A-Tat Rap"]]),

    "GL Entryway Jiggy": LocationData(120013, [["Jump"], ["Feathery Flap"], ["Flap Flip"], ["Rat-A-Tat Rap"]]),
    "GL Atop Mumbo's Mountain Jiggy": LocationData(120014),
    "GL Treasure Trove Cove Cannon Jiggy": LocationData(120015, [["Flap Flip", "Beak Buster", "Flight"]]),

    "GL Mumbo Token Behind Red Magic Cauldron": LocationData(999999),
    "GL Mumbo Token Above Drain Pipe": LocationData(999999),
    "GL Mumbo Token Near Click Clock Wood Podium": LocationData(999999, [["Climb", "Swim"]]),

    "MM Conga Orange Throw Jiggy": LocationData(120014),
    "MM Chimpy Orange Jiggy": LocationData(120015, [["Climb"]]),
    "MM Conga Attack Jiggy": LocationData(120016, [["Flap Flip", "Eggs"]]),
    "MM Stonehenge Jiggy": LocationData(120017),
    "MM Hillside Jiggy": LocationData(120018),
    "MM Mumbo's Hut Jiggy": LocationData(120019, [["Flap Flip"]]),
    "MM Totem Pole Jiggy": LocationData(120020, [["Jump", "Egg"], ["Flap Flip, Egg"]]),
    "MM Hut Jiggy": LocationData(120021, [["Jump", "Beak Buster"], ["Flap Flip, Beak Buster"]]),
    "MM Top of Termite Mountain Jiggy": LocationData(120022),
    "MM Blue Jinjo": LocationData(120023, [["Jump"], ["Feathery Flap"]]),
    "MM Green Jinjo": LocationData(12024, [["Jump", "Beak Buster"], ["Flap Flip", "Beak Buster"]]),
    "MM Orange Jinjo": LocationData(12025, [["Talon Trot"]]),
    "MM Pink Jinjo": LocationData(120026, [["Flap Flip"]]),
    "MM Yellow Jinjo": LocationData(12027),
    "MM Jinjo Jiggy": LocationData(12028, [["Jump", "Beak Buster", "Talon Trot", "Flap Flip"], ["Feathery Flap", "Beak Buster", "Talon Trot", "Flap Flip"]]),
    "MM Egg Molehill": LocationData(12029, [["Flap Flip", "Climb"]]),
    "MM Talon Trot Molehill": LocationData(12030),
    "MM Beak Buster Molehill": LocationData(12031),
    "MM Hillside Honeycomb Piece": LocationData(12032),
    "MM Totem Pole Honeycomb Piece": LocationData(12033, [["Flap Flip", "Eggs"]]),
    "MM Mumbo Token Behind Pink Jinjo": LocationData(12034),
    "MM Mumbo Token By Conga": LocationData(12035, [["Flap Flip", "Climb"]]),
    "MM Mumbo Token Behind Stonehenge": LocationData(99999),
    "MM Mumbo Token in Termite Mountain": LocationData(99999, [["Talon Trot"]]),
    "MM Mumbo Token by Mumbo's Hut": LocationData(99999),

    "TTC Nipper Jiggy": LocationData(99999, [["Jump", "Rat-A-Tat Rap"], ["Flap Flip", "Rat-A-Tat Rap"]]),
    "TTC Blubber's Jiggy": LocationData(99999, [["Flap Flip", "Swim", "Beak Buster"]]),
    "TTC Sandcastle Jiggy": LocationData(99999, [["Flap Flip", "Eggs", "Beak Buster"]]),
    "TTC Shock Spring Jump Jiggy": LocationData(99999, [["Shock Spring Jump"]]),
    "TTC X Marks the Spot Jiggy": LocationData(99999 [["Beak Buster", "Flight"], ["Beak Buster", "Shock Spring Jump"]]),
    "TTC Underwater Pool Jiggy": LocationData(99999, [["Swim"]]),
    "TTC Cliffside Jiggy": LocationData(99999),
    "TTC Lockup Jiggy": LocationData(99999, [["Flap Flip", "Swim"]]),
    "TTC Lighthouse Jiggy": LocationData(99999, [["Flight"]]),
    "TTC Jinjo Jiggy": LocationData(99999, [["Swim, Flight"]]),
    "TTC Blue Jinjo": LocationData(99999, [["Swim"]]),
    "TTC Green Jinjo": LocationData(99999, [["Climb"], ["Flight"]]),
    "TTC Orange Jinjo": LocationData(99999),
    "TTC Pink Jinjo": LocationData(99999, [["Shock Spring Jump"], ["Jump", "Feathery Flap"], ["Flight"]]),
    "TTC Yellow Jinjo": LocationData(99999, [["Flight"]]),
    "TTC Flight Molehill": LocationData(99999, [["Talon Trot"], ["Flight"]]),
    "TTC Shock Spring Jump Molehill": LocationData(99999),
    "TTC Underwater Honeycomb Piece": LocationData(99999, [["Swim"]]),
    "TTC Floating Crate Honeycomb Piece": LocationData(99999),
    "TTC Mumbo Token in Blubber's Mast": LocationData(99999, [["Climb"]]),
    "TTC Mumbo Token in Blubber's Hold": LocationData(99999, [["Flap Flip", "Swim", "Beak Buster"]]),
    "TTC Mumbo Token near Shock Spring Jump Molehill": LocationData(99999, [["Shock Spring Jump"], ["Flight"]]),
    "TTC Mumbo Token by Treasure Box Island": LocationData(99999),
    "TTC Left Mumbo Token inside Lockup": LocationData(99999, [["Flap Flip"]]),
    "TTC Right Mumbo Token inside Lockup": LocationData(99999, [["Flap Flip"]]),
    "TTC Mumbo Token in Underwater Pool": LocationData(99999, [["Swim"]]),
    "TTC Mumbo Token Above Floating Crate": LocationData(99999),
    "TTC Mumbo Token in Lighthouse": LocationData(99999, [["Flight"]]),

    "CC Raising Clanker Jiggy": LocationData(99999, [["Swim"]]),
    "CC Above Clanker's Tail Jiggy": LocationData(99999, [["Rat-A-Tat Rap", "Swim"]]),
    "CC Above Clanker's Bolt Jiggy": LocationData(99999, [["Flap Flip", "Swim"]]),
    "CC Clanker's Second Gold Tooth Jiggy": LocationData(99999, [["Swim", "Eggs"]]),
    "CC Inside Clanker's Blowhole Jiggy": LocationData(99999, [["Swim"]]),
    "CC Wonderwing Jiggy": LocationData(99999, [["Swim", "Flight", "Wonderwing"]]),
    "CC Clanker's Rings Jiggy": LocationData(99999, [["Jump", "Swim", "Feathery Flap"], ["Jump", "Swim", "Rat-A-Tat Rap"]]),
    "CC Snippet Jiggy": LocationData(99999, [["Swim", "Flap Flip", "Claw Swipe"], ["Swim", "Flap Flip", "Roll"], ["Swim", "Flap Flip", "Beak Barge"], ["Swim", "Flap Flip", "Beak Buster"]]),
    "CC Underwater Tunnel Jiggy": LocationData(99999, [["Swim"]]),
    "CC Jinjo Jiggy": LocationData(99999, [["Swim", "Climb", "Feathery Flap", "Beak Buster", "Shock Spring Jump"], ["Swim", "Climb", "Rat-A-Tat Rap", "Beak Buster", "Shock Spring Jump"]]),
    "CC Blue Jinjo": LocationData(99999, [["Swim"]]),
    "CC GreenJinjo": LocationData(99999, [["Swim"]]),
    "CC Orange Jinjo": LocationData(99999, [["Swim", "Climb", "Feathery Flap", "Beak Buster", "Shock Spring Jump"], ["Swim", "Climb", "Rat-A-Tat Rap", "Beak Buster", "Shock Spring Jump"]]),
    "CC Pink Jinjo": LocationData(99999, [["Swim"]]),
    "CC Yellow Jinjo": LocationData(99999, [["Feathery Flap", "Climb"], ["Rat-A-Tat Rap", "Climb"]]),
    "CC Wonderwing Molehill": LocationData(99999, [["Swim", "Flight"]]),
    "CC Inside Pipe Honeycomb Piece": LocationData(99999, [["Swim"]]),
    "CC Inside Wall Grate Honeycomb Piece": LocationData(99999, [["Swim", "Climb", "Feathery Flap", "Talon Trot", "Beak Buster", "Shock Spring Jump"], ["Swim", "Climb", "Rat-A-Tat Rap", "Talon Trot", "Beak Buster", "Shock Spring Jump"]]),
    "CC Mumbo Token Above Entrance": LocationData(99999, [["Jump", "Feathery Flap", "Climb"], ["Jump", "Rat-A-Tat Rap", "Climb"]]),
    "CC Mumbo Token Above Clanker's Tail": LocationData(99999, [["Swim"]]),
    "CC Mumbo Token in Clanker's First Gold Tooth":  LocationData(99999, [["Swim", "Eggs"]]),
    "CC Mumbo Token in High Grate": LocationData(99999, [["Swim", "Climb", "Shock Spring Jump"]]),


#    "Banjo's House": 12000,
#    "Spiral Mountain": 12001,
#    "Grunty's Lair 1F": 12002,
#    "Grunty's Lair 2F": 12003,
#    "Grunty's Lair 3F:": 12004,
#    "Grunty's Lair Trove Entrance": 12005,
#    "Grunty's Lair Clanker Entrance": 12006,
#    "Grunty's Lair 4F": 12007,
#    "Grunty's Lair Swamp Entrance": 12008,
#    "Grunty's Lair 5F": 12009,
#    "Grunty's Lair 6F": 12010,
#    "Grunty's Lair Magma Room": 12011,
#    "Grunty's Lair Graveyard": 12012,
#    "Grunty's Lair Mumbo's Hut": 12013,
#    "Grunty's Lair 7F": 12014,
#    "Grunty's Lair Shipyard": 12015,
#    "Grunty's Lair 8F": 12016,
#    "Grunty's Lair Game Show": 12017,
#    "Grunty's Lair Top": 12018,
#    "Grunty's Lair Arena": 12019,
#    "Mumbo's Mountain Hub": 12020,
#    "Mumbo's Mountain Mumbo's Hut": 12021,
#    "Mumbo's Mountain Termite Hill": 12022,
#    "Treasure Trove Cove Hub": 12023,
#    "Treasure Trove Cove Sandcastle Room": 12024,
#    "Treasure Trove Cove Sharkfood Island Cave": 12025,
#    "Treasure Trove Cove Crab Shell": 12026,
#    "Treasure Trove Cove Ship Entrance A": 12027,
#    "Treasure Trove Cove Ship Entrance B": 12028,
#    "Clanker's Cavern Hub": 12029,
#    "Clanker's Cavern Clanker's Head": 12030,
#    "Clanker's Cavern Clanker's Mouth": 12031,
#    "Clanker's Cavern Clanker's Stomach": 12032,
#    "Bubblegloop Swamp Hub": 12033,
#    "Bubblegloop Swamp Mumbo's Hut": 12034,
#    "Bubblegloop Swamp Inside Alligator": 12035,
#    "Bubblegloop Swamp Inside Tanktup": 12036,
#    "Freezeezy Peak Hub": 12037,
#    "Freezeezy Peak Boggy's Igloo": 12038,
#    "Freezeezy Peak Wozza's Cave": 12039,
#    "Freezeezy Peak Christmas Tree": 12040,
#    "Freezeezy Peak Mumbo's Hut": 12041,
#    "Gobi's Valley Hub": 12042,
#    "Gobi's Valley Inside Jinxy": 12043,
#    "Gobi's Valley Egg Cave": 12044,
#    "Gobi's Valley Rubee's Pyramid": 12045,
#    "Gobi's Valley Water Pyramid": 12046,
#    "Gobi's Valley Panel Puzzle Pyramid": 12047,
#    "Gobi's Valley Sandybutt's Tomb": 12048,
#    "Mad Monster Mansion Hub": 12049,
#    "Mad Monster Mansion Dining Room": 12050,
#    "Mad Monster Mansion Bathroom": 12051,
#    "Mad Monster Mansion Bedroom": 12052,
#    "Mad Monster Mansion Rafters": 12053,
#    "Mad Monster Mansion Cellar": 12054,
#    "Mad Monster Mansion Well": 12055,
#    "Mad Monster Mansion Tumblar's Shack": 12056,
#    "Mad Monster Mansion Church": 12057,
#    "Mad Monster Mansion Gutter": 12058,
#    "Mad Monster Mansion Mumbo's Hut": 12059,
#    "Rusty Bucket Bay Hub": 12060,
#    "Rusty Bucket Bay Engine Room": 12061,
#    "Rusty Bucket Bay Captain's Cabin": 12062,
#    "Rusty Bucket Bay Barracks": 12063,
#    "Rusty Bucket Bay Kitchen": 12064,
#    "Rusty Bucket Bay Map Room": 12065,
#    "Rusty Bucket Bay Cargo Hold": 12066,
#    "Rusty Bucket Bay Anchor Hold": 12067,
#    "Rusty Bucket Bay Storage Crate A": 12068,
#    "Rusty Bucket Bay Storage Crate B": 12069,
#    "Rusty Bucket Bay Storage Crate C": 12070,
#    "Rusty Bucket Bay Broken Window": 12071,
#    "Rusty Bucket Bay Water Warehouse": 12072,
#    "Rusty Bucket Bay Snacker Warehouse": 12073,
#    "Click Clock Wood Hub": 12074,
#    "Click Clock Wood Spring Hub": 12075,
#    "Click Clock Wood Spring Mumbo's Hut": 12076,
#    "Click Clock Wood Spring Nabnut's House": 12077,
#    "Click Clock Wood Spring Zubba's Nest": 12078,
#    "Click Clock Wood Summer Hub": 12079,
#    "Click Clock Wood Summer Mumbo's Hut": 12080,
#    "Click Clock Wood Summer Nabnut's House": 12081,
#    "Click Clock Wood Summer Zubba's Nest": 12082,
#    "Click Clock Wood Autumn Hub": 12083,
#    "Click Clock Wood Autumn Mumbo's Hut": 12084,
#    "Click Clock Wood Autumn Nabnut's House": 12085,
#    "Click Clock Wood Autumn Zubba's Nest": 12086,
#    "Click Clock Wood Winter Hub": 12087,
#    "Click Clock Wood Winter Mumbo's Hut": 12088,
#    "Click Clock Wood Winter Nabnut's House": 12089,
#    "Click Clock Wood Nut Storage Room": 12090,
#    "Click Clock Wood Treetop Room": 12091,###
}

